theme = "jb-darcula"
# theme = "base16_default"

[editor]
line-number = "relative"
auto-save = true
bufferline = "multiple"
cursorline = true
idle-timeout = 200
terminal.command = "bash"
terminal.args = ["-c"]
end-of-line-diagnostics = "hint"
rainbow-brackets = true

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.file-picker]
hidden = false

[editor.gutters.line-numbers]
min-width = 41

[editor.indent-guides]
render = true
character = "|" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[editor.lsp]
# display-inlay-hints = true
display-messages = true
goto-reference-include-declaration = false

[editor.soft-wrap]
enable = true

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name", "version-control"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
#separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.inline-diagnostics]
# Minimum severity to show a diagnostic on the primary cursor's line.
# Note that `cursor-line` diagnostics are hidden in insert mode.
cursor-line = "hint"
# Minimum severity to show a diagnostic on other lines:
other-lines = "disable"

[icons.vcs]
enabled = true

[icons.fs]
enabled = true

[keys.normal]
"{" = ["goto_prev_paragraph", "collapse_selection"]
"}" = ["goto_next_paragraph", "collapse_selection"]
0 = "goto_line_start"
"$" = "goto_line_end"
G = "goto_file_end"
V = ["select_mode", "extend_to_line_bounds"]
Z = { Z = ":x" }

x = "delete_selection"

# w = ["move_next_word_start", "collapse_selection", "move_char_right"]
b = ["move_prev_word_start", "collapse_selection"]

"ret" = "goto_word"

"tab" = "goto_next_buffer"
"S-tab" = "goto_previous_buffer"

C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]

[keys.normal.d]
d = ["extend_to_line_bounds", "yank_main_selection_to_clipboard", "delete_selection"]

[keys.normal.y]
y = ["extend_to_line_bounds", "yank_main_selection_to_clipboard", "normal_mode", "collapse_selection"]

[keys.normal.space]
z = ":toggle gutters.line-numbers.min-width 41 3"

[keys.normal.";"]
a = [
    ":set gutters.line-numbers.min-width 3",
    ":sh helix-wezterm.sh opencode"
]
b = ":sh helix-wezterm.sh blame %{buffer_name} %{cursor_line}"
c = ":sh helix-wezterm.sh check"
d = ":sh helix-wezterm.sh doc %{buffer_name}"
# D = "@%s@Disabled<ret>Vd,"
e = [
    ':sh rm -f /tmp/unique-file',
    ':insert-output yazi %{buffer_name} --chooser-file=/tmp/unique-file',
    ':insert-output echo "\x1b[?1049h\x1b[?2004h" > /dev/tty',
    ':open %sh{cat /tmp/unique-file}',
    ':redraw',
]
E = [
    ':sh rm -f /tmp/unique-file',
    ':insert-output yazi --chooser-file=/tmp/unique-file',
    ':insert-output echo "\x1b[?1049h\x1b[?2004h" > /dev/tty',
    ':open %sh{cat /tmp/unique-file}',
    ':redraw',
]
f = [
    ":set gutters.line-numbers.min-width 3",
    ":sh helix-wezterm.sh tree"
]
# f = "file_browser"
# g = ":sh osascript /Users/quantong/Code/personal/helix-wezterm/ghostty.applescript lazygit"
# g = [
#     ":write-all", 
#     ":new", 
#     ":insert-output lazygit", 
#     ":buffer-close!", 
#     ":redraw", 
#     ":reload-all"
# ]
g = ":sh helix-wezterm.sh lazygit"
i = ":sh helix-wezterm.sh install %{buffer_name}"
j = ":sh helix-wezterm.sh jira"
k = ":sh helix-wezterm.sh k9s"
l = ":sh helix-wezterm.sh logs"
o = ":sh helix-wezterm.sh open %{buffer_name} %{cursor_line}"
# q = ":sh helix-wezterm.sh query"
q = [
    ":write-all", 
    ":new", 
    ":insert-output lazysql", 
    ":buffer-close!", 
    ":redraw", 
    ":reload-all"
]
r = ":sh helix-wezterm.sh run %{buffer_name} %{cursor_line} > /tmp/run.log 2>&1"
# s = ":sh helix-wezterm.sh slumber"
m = ":sh helix-wezterm.sh mock > /tmp/mock.log 2>&1"
# n = ":sh helix-wezterm.sh generate_tests"
n = ":sh helix-wezterm.sh navi"
s = ":sh helix-wezterm.sh presenterm %{buffer_name}"
# s = ":sh helix-wezterm.sh exercism_submit %{buffer_name}"
# s = [
#     ":write-all",
#     ":insert-output scooter >/dev/tty",
#     ":redraw",
#     ":reload-all"
# ]
t = ":sh helix-wezterm.sh test %{buffer_name} %{cursor_line} > /tmp/test.log 2>&1"
v = ":sh helix-wezterm.sh vault > /dev/null 2>&1"
w = [
    ":set gutters.line-numbers.min-width 3",
    ":sh helix-wezterm.sh watch %{buffer_name}"
]

[keys.select]
"{" = ["extend_to_line_bounds", "goto_prev_paragraph"]
"}" = ["extend_to_line_bounds", "goto_next_paragraph"]
G = "goto_file_end"

j = ["extend_line_down", "extend_to_line_bounds"]
k = ["extend_line_up", "extend_to_line_bounds"]

d = ["yank_main_selection_to_clipboard", "delete_selection"]
x = ["yank_main_selection_to_clipboard", "delete_selection"]

"ret" = "extend_to_word"

[keys.select.";"]
j = ["yank_to_clipboard", ":sh helix-wezterm.sh jq"]
a = [
    ":set gutters.line-numbers.min-width 3",
    "yank_to_clipboard",
    ":sh helix-wezterm.sh ai %{buffer_name} %{cursor_line} %{selection_line_start} %{selection_line_end} > /tmp/ai.log 2>&1",
    "collapse_selection"
]
q = ["yank_to_clipboard", "collapse_selection", ":insert-output pbpaste | quicktype -l go"]
m = [":pipe-to mmdc --input - -o output.png", ":sh open output.png"]
r = [
    "yank_to_clipboard",
    ":sh bottom_pane=$(wezterm cli get-pane-direction Down); pbpaste > playground/src/main.rs; wezterm cli zoom-pane --unzoom; echo 'cargo run --manifest-path playground/Cargo.toml' | wezterm cli send-text --pane-id $bottom_pane --no-paste"
]
v = [
    "yank_to_clipboard",
    ":sh helix-wezterm.sh validate %{buffer_name}"
]

# [keys.insert]
# C-a = "inline_completion_accept"
# C-e = "inline_completion_dismiss"
# C-n = "inline_completion_next"
# C-p = "inline_completion_prev"
# C-space = "inline_completion_trigger"
